#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: Zhensheng
 * Date: 2018/11/16
 * Time: 23:00
 */

namespace SmartCCDGUT;

abstract class Constants
{
    const SCHEMA = "https";

    const HOST = "smart.ccdgut.edu.cn";

    const SLAT = 'jw134#%pqNLVfn';

    const APP_URIS = [
        "login" => "/app/user/login",
        "logout" => "/app/user/logout",
    ];

    const URLS = [
    ];

    const USER_DIRECTORY = __DIR__ . "/users/";

    const CREDENTIAL_FILE_NAME = "credentials";

    const USER_FILE_NAME = "user";

    public static function namedUrl($name)
    {
        if (array_key_exists($name, static::APP_URIS)) {
            return static::url(static::APP_URIS[$name]);
        }
        if (array_key_exists($name, static::URLS)) {
            return static::URLS[$name];
        }
        return null;
    }

    public static function url($uri)
    {
        return sprintf("%s://%s%s", Constants::SCHEMA, Constants::HOST, $uri);
    }

    public static function hasher($plainText)
    {
        return md5(md5(Constants::SLAT . $plainText));
    }

    public static function userCredentialFilePath($username)
    {
        @mkdir(static::USER_DIRECTORY . $username, 0700, true);
        return sprintf("%s%s/%s", static::USER_DIRECTORY, $username, static::CREDENTIAL_FILE_NAME);
    }

    public static function userFilePath($username)
    {
        @mkdir(static::USER_DIRECTORY . $username, 0700, true);
        return sprintf("%s%s/%s", static::USER_DIRECTORY, $username, static::USER_FILE_NAME);
    }
}

if (!function_exists("\\readline")) {
    function readline($prompt = "")
    {
        echo $prompt;
        return stream_get_line(STDIN, 1024, PHP_EOL);
    }
}

final class Common
{
    final public static function readline($prompt)
    {
        return readline($prompt);
    }

    final public static function log($text)
    {
        self::fprintf(STDOUT, $text);
    }

    final public static function logf($format, ... $args)
    {
        self::fprintf(STDOUT, $format, ... $args);
    }

    final public static function error($text)
    {
        self::fprintf(STDERR, $text);
    }

    final public static function errorf($format, ... $args)
    {
        self::fprintf(STDERR, $format, ... $args);
    }

    private static function fprintf($resource, $format, ... $args)
    {
        return \fprintf($resource, $format, ... $args);
    }
}

class SmartCCDGUTException extends \Exception
{
}

/**
 * Class Argv
 * @package SmartCCDGUT
 * @property-read array $originArgv
 * @property-read array $argv
 * @property-read string $file
 * @property-read string $command
 */
class Argv
{
    /**
     * @var Argv $globalInstance
     */
    public static $globalInstance;

    private $originArgv;

    private $argv;

    private $file;

    private $command;

    public function __construct($argv = null)
    {
        if (is_null($argv)) {
            $argv = $_SERVER["argv"];
        }

        $this->originArgv = $argv;

        $this->file = @array_shift($argv);
        $this->command = @array_shift($argv);

        $this->argv = $argv;
    }

    public function setAsGlobal()
    {
        static::$globalInstance = $this;
        return $this;
    }

    public function __get($name)
    {
        return $this->{$name};
    }

    public function at($index)
    {
        return @$this->argv[$index];
    }

    public function atOrigin($index)
    {
        return @$this->originArgv[$index];
    }
}

class CommandRouter
{
    private $controllers = [];

    private $singletons = [];

    private $singletonInstances = [];

    private $normalProviders = [];

    private $names = [];

    /**
     * @var Argv
     */
    private $argv;

    public function __construct(Argv $argv)
    {
        $this->argv = $argv;

        $this->controllers = [
            "login" => SmartCCDGUTLoginController::class . "@login",
            "logout" => SmartCCDGUTLoginController::class . "@logout",
            "electric" => SmartCCDGUTElectricQueryController::class . "@query",
            "attendance" => SmartCCDGUTAttendanceController::class . "@query",
            "extraCredit" => SmartCCDGUTExtraCredit::class . "@query",
        ];

        $this->singletons = [
            Argv::class => Argv::class,
        ];

        $this->singletonInstances[Argv::class] = $argv;

        $credentialCreator = function () {
            $username = $this->argv->at(0);
            if (empty($username)) {
                throw new SmartCCDGUTException("username is required by command " . $this->argv->command . ".");
            }
            $userCredentialFilePath = Constants::userCredentialFilePath($username);
            if (!file_exists($userCredentialFilePath)) {
                throw new SmartCCDGUTException("User " . $username . " not login.");
            }
            $decodedContent = json_decode(file_get_contents($userCredentialFilePath));
            if (is_null($decodedContent)) {
                throw new SmartCCDGUTException("Invalid credential file: " . json_last_error_msg());
            }

            $credential = new Credential($decodedContent->userToken, $decodedContent->token,
                $decodedContent->userId);
            // $credential->setAsGlobal();
            return $credential;
        };

        $this->normalProviders = [
            SmartCCDGUTNetwork::class => function () use ($credentialCreator) {
                // These urls required token
                static $tokenRequiredUrls = [
                    "electric" => "https://smart-ccdgut.com/elecharge/data.php",
                    "attendance" => "http://wx.ccdgut.edu.cn:9000/zhcy.htm",
                    "extraCredit" => "http://218.16.63.158:8990/remote/token",
                ];

                // These commands required login
                static $loginRequiredCommands = [
                    "logout" => true,
                    "electric" => true,
                    "attendance" => true,
                    "extraCredit" => true,
                ];

                $command = $this->argv->command;

                $smartCCDGUTNetwork = new SmartCCDGUTNetwork();

                if (array_key_exists($command, $loginRequiredCommands)) {
                    $credential = $credentialCreator();
                    $smartCCDGUTNetwork->setCredential($credential);
                }

                if (array_key_exists($command, $tokenRequiredUrls)) {
                    // Create token url
                    $apiUrl = sprintf("%s?needLogin=1&token=%s&XPS-UserId=%s&", $tokenRequiredUrls[$command],
                        $credential->token, $credential->userId);
                } else {
                    $apiUrl = Constants::namedUrl($command);
                }

                $smartCCDGUTNetwork->setApiUrl($apiUrl);

                return $smartCCDGUTNetwork;
            },
            Credential::class => $credentialCreator,
            DOMDocumentOperator::class => function () {
                return new PHPDOMDocument();
            },
        ];

        $this->names = [
            "apiUrl" => function () {
                return Constants::namedUrl($this->argv->command);
            },
        ];
    }

    public static function start()
    {
        try {
            $argv = new Argv();
            $argv->setAsGlobal();

            $commandRouter = new CommandRouter($argv);
            $result = $commandRouter->run();

            if (is_string($result)) {
                Common::log($result);
            } else {
                var_dump($result);
            }
        } catch (SmartCCDGUTException $e) {
            Common::errorf("[CODE %d]: %s" . PHP_EOL, $e->getCode(), $e->getMessage());
        }
    }

    public function run()
    {
        $controller = self::make($this->argv->command);

        $parameters = $this->resolveParameters($controller);

        return call_user_func($controller, ... $parameters);
    }

    public static function helpMessage()
    {
        Common::errorf("Usage: %s COMMAND%s", __FILE__, PHP_EOL);
        Common::errorf("Available commands:" . PHP_EOL);
        Common::errorf("\tlogin [USERNAME] [PASSWORD]\t\tLogin to Smart CCDGUT and save token." . PHP_EOL);
        Common::errorf("\tlogout USERNAME \t\tLogout." . PHP_EOL);
        Common::errorf(PHP_EOL);
        Common::errorf("\telectric USERNAME\t\tQuery electric usage details." . PHP_EOL);
        Common::errorf("\tattendance USERNAME\t\tQuery attendance details." . PHP_EOL);
        Common::errorf("\textraCredit USERNAME\t\tQuery extraCredit details." . PHP_EOL);
        Common::errorf(PHP_EOL . PHP_EOL);
        Common::errorf("Zhensheng Yuan: https://zhensheng.im." . PHP_EOL);
    }

    private function make($command)
    {
        if (!array_key_exists($command, $this->controllers)) {
            static::helpMessage();
            exit(1);
        }

        $controller = $this->controllers[$command];
        if (is_callable($controller)) {
            return $controller;
        }

        @list($controllerClass, $method) = explode("@", $controller, 2);
        $controllerObject = new $controllerClass;
        if (empty($method)) {
            return $controllerObject;
        }
        return [$controllerObject, $method];
    }

    private function resolveParameters($callable)
    {
        $parameters = [];
        $reflectionParameters = $this->getParameters($callable);
        $argvIndex = 0;
        foreach ($reflectionParameters as $index => $parameter) {
            $parameterName = $parameter->getName();
            if ($parameter->hasType()) {
                $reflectionClass = $parameter->getClass();
                $className = $reflectionClass->getName();

                // Is singleton?
                if (array_key_exists($className, $this->singletons)) {
                    // Is instance exists?
                    if (!array_key_exists($className, $this->singletonInstances)) {
                        // Create instance and store it on not exists
                        if (is_callable($this->singletons[$className])) {
                            $instance = call_user_func($this->singletons[$className]);
                        } else {
                            $instance = new $className;
                        }
                        $this->singletonInstances[$className] = $instance;
                    }

                    // Add singleton instance to $parameters
                    $parameters[] = $this->singletonInstances[$className];
                } else {
                    if (array_key_exists($className, $this->normalProviders)) {
                        $parameters[] = call_user_func($this->normalProviders[$className]);
                    } else {
                        // Simply create an instance
                        $parameters[] = new $className;
                    }
                }
            } else {
                if (array_key_exists($parameterName, $this->names)) {
                    $parameters[] = call_user_func($this->names[$parameterName]);
                } else {
                    // Simply retrieve next argv
                    $parameters[] = $this->argv->at($argvIndex++);
                }
            }
        }

        return $parameters;
    }

    private function getParameters($callable)
    {
        $CReflection = is_array($callable) ? new \ReflectionMethod($callable[0],
            $callable[1]) : new \ReflectionFunction($callable);
        return $CReflection->getParameters();
    }
}

class Credential
{
    /**
     * @var Credential
     */
    public static $globalInstance;

    public $userToken;
    public $token;
    public $userId;

    public function __construct($userToken = null, $token = null, $userId = null)
    {
        $this->userToken = $userToken;
        $this->token = $token;
        $this->userId = $userId;
    }

    public function setAsGlobal()
    {
        self::$globalInstance = $this;
    }
}

class SmartCCDGUTLoginController
{
    /**
     * @param SmartCCDGUTNetwork $smartCCDGUTNetwork
     * @param string|null $username
     * @param string|null $password
     * @return string
     * @throws SmartCCDGUTException
     * @throws SmartCCDGUTNetworkException
     */
    public function login(SmartCCDGUTNetwork $smartCCDGUTNetwork, $username = null, $password = null)
    {
        if (empty($username)) {
            $username = Common::readline("Username: ");
        }

        if (empty($password)) {
            $password = Common::readline("Password: ");
        }

        $credential = new Credential();

        $smartCCDGUTNetwork
            ->curlSetopt(function ($ch) use ($credential) {
                curl_setopt($ch, CURLOPT_HEADERFUNCTION, function ($ch, $header) use ($credential) {
                    @list($name, $value) = explode(": ", $header, 2);
                    $name = trim($name);
                    $value = trim($value);
                    switch ($name) {
                        case "XPS-UserToken":
                            $credential->userToken = $value;
                            break;
                        case "XPS-Token":
                            $credential->token = $value;
                            break;
                        case "XPS-UserId":
                            $credential->userId = $value;
                            break;
                    }
                    return strlen($header);
                });
            })
            ->addPostField("account", $username)
            ->addPostField("password", Constants::hasher($password))
            ->addPostField("sign", "2");

        $result = $smartCCDGUTNetwork->preformDecodeOrFail();
        if ($result->result == "0") {
            throw new SmartCCDGUTNetworkException($result->msg);
        }

        if (empty($credential->userToken) || empty($credential->token) || empty($credential->userId)) {
            throw new SmartCCDGUTException("Login failed with invalid token.");
        }

        file_put_contents(Constants::userCredentialFilePath($username), json_encode($credential));
        file_put_contents(Constants::userFilePath($username), json_encode($result->item));

        $text = sprintf("Hello, %s.%s", $result->item->xm, PHP_EOL);
        $text .= "Login successfully with credentials save to " . Constants::userCredentialFilePath($username) . "." . PHP_EOL;

        return $text;
    }

    /**
     * @param SmartCCDGUTNetwork $smartCCDGUTNetwork
     * @return string
     * @throws SmartCCDGUTException
     * @throws SmartCCDGUTNetworkException
     */
    public function logout(SmartCCDGUTNetwork $smartCCDGUTNetwork, $username)
    {
        $smartCCDGUTNetwork->curlSetopt(function ($ch) {
            curl_setopt($ch, CURLOPT_POST, true);
        });

        $result = $smartCCDGUTNetwork->preformDecodeOrFail();
        if ($result->result == "1") {
            unlink(Constants::userCredentialFilePath($username));
            unlink(Constants::userFilePath($username));
            return "Logout successfully." . PHP_EOL;
        }
        throw new SmartCCDGUTException("Logout unsuccessfully.");
    }
}

class SmartCCDGUTElectricQueryController
{
    const AVAILABLE_AREAS = [
        "01" => "学1A",
        "02" => "学1B",
        "03" => "学1C",
        "04" => "学1D",
        "05" => "学2A",
        "06" => "学2B",
        "07" => "学2C",
        "08" => "学2D",
        "09" => "学3A",
        "10" => "学3B",
        "11" => "学3C",
        "12" => "学3D",
        "13" => "学4A",
        "14" => "学4B",
        "15" => "学4C",
        "16" => "学4D",
        "17" => "学5A",
        "18" => "学5B",
        "19" => "学5C",
        "20" => "学5D",
        "21" => "学6A",
        "22" => "学6B",
        "23" => "学6C",
        "24" => "学6D",
        "25" => "学7A",
        "26" => "学7B",
        "27" => "学7C",
        "28" => "学8A",
        "29" => "学8B",
        "30" => "学8C",
        "31" => "学9A",
        "32" => "学9B",
        "33" => "学9C",
        "34" => "学10",
        "35" => "学11",
        "36" => "学12",
    ];

    public function query(
        Credential $credential,
        SmartCCDGUTNetwork $smartCCDGUTNetwork,
        $username,
        $area = null,
        $room = null
    ) {
        if (empty($area)) {
            Common::logf("%s%s", "Available areas: ", PHP_EOL);
            Common::logf("%s%s", "Code\t\tName", PHP_EOL);
            foreach (static::AVAILABLE_AREAS as $code => $name) {
                Common::logf("%s\t\t%s%s", $code, $name, PHP_EOL);
            }
            Common::log(PHP_EOL);
            $area = Common::readline("Please select your area by code: ");
        }

        if (empty($room)) {
            $room = Common::readline("Please input your room no: ");
        }

        $smartCCDGUTNetwork
            ->addHeader("Referer: https://smart-ccdgut.com/elecharge/index.php")
            ->addPostField("loudong", $area)
            ->addPostField("sushe", $room)
            ->addPostField("token", $credential->token)
            ->addPostField("isBind", "1");

        $result = $smartCCDGUTNetwork->preformDecodeOrFail();
        if ($result->errorNumber != 1) {
            throw new SmartCCDGUTException("Query unsuccessfully", $result->errorNumber);
        }

        $text = sprintf("Electric credit: %s%s%s", $result->remainelectric, PHP_EOL, PHP_EOL);
        $usage = $result->table;
        while ($date = array_shift($usage)) {
            $v = array_shift($usage);
            $text .= sprintf("%s => %s%s", $date, $v, PHP_EOL);
        }

        return $text;
    }
}

class SmartCCDGUTAttendanceController
{
    public function query(
        SmartCCDGUTNetwork $smartCCDGUTNetwork,
        DOMDocumentOperator $DOMDocumentOperator
    ) {
        $html = $smartCCDGUTNetwork->preformOrFail();
        $DOMDocumentOperator->setHTML($html);

        $elements = $DOMDocumentOperator->getElementByClass("card");

        $text = "";

        foreach ($elements as $element) {
            $cardChildElements = $element->getChildElements();
            $time = trim($cardChildElements[1]->getTextContent());
            $lesson = trim($cardChildElements[3]->getTextContent());

            $text .= sprintf("%s => %s%s", $time, $lesson, PHP_EOL);
        }

        return $text;
    }
}

class SmartCCDGUTExtraCredit
{
    public function query(
        SmartCCDGUTNetwork $smartCCDGUTNetwork,
        DOMDocumentOperator $DOMDocumentOperator
    ) {
        $html = $smartCCDGUTNetwork->preformOrFail();
        $DOMDocumentOperator->setHTML($html);

        $items = $DOMDocumentOperator->getElementByClass("mui-media-body");

        $summary = trim(array_shift($items)->getTextContent());

        $text = $summary . PHP_EOL . PHP_EOL;

        foreach ($items as $DOMElementOperator) {
            $childElements = $DOMElementOperator->getChildElements();
            $itemName = trim($childElements[0]->getText());
            $itemCredit = trim($childElements[1]->getTextContent());
            $itemStatus = trim($childElements[3]->getChildElements()[1]->getTextContent());

            $text .= sprintf("%s". PHP_EOL ."\t%s\t%s" . PHP_EOL . PHP_EOL, $itemName, $itemCredit, $itemStatus);
        }

        return $text;
    }
}

class DOMException extends SmartCCDGUTException
{

}

interface DOMDocumentOperator
{
    /**
     * @return \DOMDocument
     */
    public function DOMDocument();

    /**
     * @return \DOMXPath
     */
    public function DOMXPath();

    /**
     * @param string $html
     * @param int $options
     * @return mixed
     */
    public function setHTML($html = "", $options = 0);

    /**
     * @param string $id
     * @return DOMElementOperator
     */
    public function getElementById($id);

    /**
     * @param string $tagName
     * @return DOMElementOperator[]
     */
    public function getElementsByTagName($tagName);

    /**
     * @param string|string[] $class
     * @return DOMElementOperator[]
     */
    public function getElementByClass($class);
}

class PHPDOMDocument implements DOMDocumentOperator
{
    /**
     * @var \DOMDocument $document
     */
    private $document;

    /**
     * @var \DOMXPath $XPath
     */
    private $XPath;

    /**
     * PHPDOMDocument constructor.
     * @param null $html
     * @param int $options
     * @throws DOMException
     */
    public function __construct($html = null, $options = 0, $charset = null)
    {
        if (!is_null($html)) {
            $this->setHTML($html, $options, $charset);
        }
    }

    /**
     * @return \DOMDocument
     */
    public function DOMDocument()
    {
        return $this->document;
    }

    public function DOMXPath()
    {
        return $this->XPath;
    }

    /**
     * @param string $html
     * @param int $options
     * @param null $charset
     * @return mixed|void
     * @throws DOMException
     */
    public function setHTML($html = "", $options = 0, $charset = null)
    {
        $this->document = new \DOMDocument();
        if (!defined("DEBUG")) {
            libxml_use_internal_errors(true);
        }
        if (!$this->document->loadHTML($html, $options)) {
            // printf(STDERR, $html);
            throw new DOMException();
        }
        if (!is_null($charset)) {
            $this->document->encoding = $charset;
        }
        libxml_clear_errors();
        $this->XPath = new \DOMXPath($this->document);
    }

    public function getElementById($id)
    {
        return new PHPDOMElement($this->document->getElementById($id));
    }

    public function getElementsByTagName($tagName)
    {
        $elements = [];
        foreach ($this->document->getElementsByTagName($tagName) as $element) {
            $elements[] = new PHPDOMElement($element);
        }

        return $elements;
    }

    public function getElementByClass($class)
    {
        $elements = [];

        if (is_array($class)) {
            $expressionSet = [];
            foreach ($class as $c) {
                $expressionSet[] = 'contains(concat(" ", normalize-space(@class), " "), " ' . $c . ' ")';
            }
            $expression = implode(" and ", $expressionSet);
        } else {
            $expression = 'contains(concat(" ", normalize-space(@class), " "), " ' . $class . ' ")';
        }

        foreach ($this->XPath->query('//*[' . $expression . ']') as $element) {
            $elements[] = new PHPDOMElement($element);
        }

        return $elements;
    }

    public function HTML()
    {
        return $this->DOMDocument()->saveHTML();
    }

    public function __call($name, $arguments)
    {
        call_user_func([$this->document, $name], ... $arguments);
    }

    public function __set($name, $value)
    {
        $this->document->{$name} = $value;
    }

    public function __get($name)
    {
        return $this->document->{$name};
    }
}

interface DOMElementOperator
{
    /**
     * @return \DOMElement
     */
    public function DOMElement();

    /**
     * @return array
     */
    public function getChildElements();

    /**
     * @return string mixed
     */
    public function getTagName();

    /**
     * @param string $name
     * @return string
     */
    public function getAttribute($name);

    /**
     * @param string $tagName
     * @return DOMElementOperator[]
     */
    public function getElementsByTagName($tagName);

    /**
     * @return string
     */
    public function getTextContent();

    /**
     * @param string $name
     * @return bool
     */
    public function hasAttribute($name);

    /**
     * @return string
     */
    public function getHTMLCode();

    /**
     * @return string
     */
    public function getInnerHTMLCode();

    /**
     * @return mixed
     */
    public function remove();
}

class PHPDOMElement implements DOMElementOperator
{
    private $element;

    public function __construct(\DOMElement $element)
    {
        $this->element = $element;
    }

    /**
     * @return \DOMElement
     */
    public function DOMElement()
    {
        return $this->element;
    }

    public function getChildElements()
    {
        $nodes = [];
        foreach ($this->element->childNodes as $node) {
            if ($node instanceof \DOMElement) {
                $nodes[] = new PHPDOMElement($node);
            } else {
                if ($node instanceof \DOMText) {
                    $nodes[] = new PHPDOMText($node);
                }
            }
        }

        return $nodes;
    }

    public function getTagName()
    {
        return $this->element->tagName;
    }

    public function getAttribute($name)
    {
        return $this->element->getAttribute($name);
    }

    public function getElementsByTagName($tagName)
    {
        $elements = [];
        foreach ($this->element->getElementsByTagName($tagName) as $element) {
            $elements[] = new PHPDOMElement($element);
        }

        return $elements;
    }

    public function getTextContent()
    {
        return $this->element->textContent;
    }

    public function hasAttribute($name)
    {
        return $this->element->hasAttribute($name);
    }

    public function getHTMLCode()
    {
        return $this->element->ownerDocument->saveHTML($this->element);
    }

    public function getInnerHTMLCode()
    {
        $innerHTML = "";
        foreach ($this->element->childNodes as $node) {
            $innerHTML .= $node->ownerDocument->saveHTML($node);
        }

        return $innerHTML;
    }

    public function remove()
    {
        $this->DOMElement()->parentNode->removeChild($this->DOMElement());
    }

    public function __call($name, $arguments)
    {
        call_user_func([$this->element, $name], ... $arguments);
    }
}

interface DOMElementFormOperator
{
    /**
     * @return array
     */
    public function formSerializeArray();

    /**
     * @return DOMElementOperator[]
     */
    public function getElements();

    /**
     * @param DOMElementOperator $select
     * @return DOMElementOperator[]
     */
    public static function getSelectOption(DOMElementOperator $select);
}

class PHPDOMElementFormOperator implements DOMElementFormOperator
{
    private $elementOperator;
    private $elements = [];

    public function __construct(DOMElementOperator $elementOperator)
    {
        $this->elementOperator = $elementOperator;
        $this->elements = $this->findFormElements();
    }

    private function findFormElements()
    {
        $elements = [];

        foreach ($this->elementOperator->getElementsByTagName("input") as $element) {
            /**
             * @var DOMElementOperator $element
             */
            $elements[$element->getAttribute("name")] = $element;
        }

        foreach ($this->elementOperator->getElementsByTagName("select") as $element) {
            /**
             * @var DOMElementOperator $element
             */
            $elements[$element->getAttribute("name")] = $element;
        }

        foreach ($this->elementOperator->getElementsByTagName("textarea") as $element) {
            /**
             * @var DOMElementOperator $element
             */
            $elements[$element->getAttribute("name")] = $element;
        }

        return $elements;
    }

    public static function getSelectOption(DOMElementOperator $select)
    {
        return $select->getElementsByTagName("option");
    }

    public function getElements()
    {
        return $this->elements;
    }

    public function formSerializeArray()
    {
        $elements = $this->findFormElements();

        $formDatas = [];
        foreach ($elements as $name => $element) {
            /**
             * @var DOMElementOperator $element
             */
            switch ($element->getTagName()) {
                case "input":
                    switch ($element->getAttribute("type")) {
                        case "button":
                        case "image":
                            continue;
                        case "radio":
                            if (!$element->hasAttribute("checked")) {
                                $formDatas[$name] = $element->getAttribute("value");
                            }
                            break;
                        default:
                            $formDatas[$name] = $element->getAttribute("value");
                    }
                    break;
                case "select":
                    foreach ($this->getSelectOption($element) as $option) {
                        /**
                         * @var \DOMElement $option
                         */
                        if ($option->hasAttribute("selected")) {
                            $formDatas[$name] = $option->getAttribute("value");
                            break;
                        }
                    }
                    break;
            }
        }

        return $formDatas;
    }
}

interface DOMTextOperator
{
    /**
     * @return string
     */
    public function getText();
}

class PHPDOMText implements DOMTextOperator
{
    private $DOMText;

    public function __construct(\DOMText $DOMText)
    {
        $this->DOMText = $DOMText;
    }

    public function getText()
    {
        return $this->DOMText->textContent;
    }

    public function __call($name, $arguments)
    {
        call_user_func([$this->DOMText, $name], ... $arguments);
    }
}

class SmartCCDGUTNetworkException extends SmartCCDGUTException
{
}

class SmartCCDGUTNetwork
{
    const DEFAULT_USER_AGENT = "iPhone/1.3 (iOS;12.1;1242x2208;s;46001;wifi)";

    private $apiUrl;

    private $userAgent;

    private $headers = [];

    private $postFields = [];

    private $ch;

    public function __construct($apiUrl = null, $userAgent = self::DEFAULT_USER_AGENT)
    {
        $this->apiUrl = $apiUrl;
        $this->userAgent = $userAgent;

        $this->addHeader("XPS-ClientCode: csxy");

        $this->ch = curl_init();
    }

    public function cURL()
    {
        return $this->ch;
    }

    public function curlSetopt($callable)
    {
        call_user_func($callable, $this->cURL());
        return $this;
    }

    public function setCredential(Credential $credential)
    {
        $this
            ->addHeader("XPS-Token: " . $credential->token)
            ->addHeader("XPS-UserId: " . $credential->userId);
        return $this;
    }

    public function setApiUrl($apiUrl)
    {
        $this->apiUrl = $apiUrl;
        return $this;
    }

    public function setPostFields($postFields)
    {
        $this->postFields = $postFields;
        return $this;
    }

    public function addPostField($name, $value)
    {
        $this->postFields[$name] = $value;
        return $this;
    }

    public function setHeaders($headers)
    {
        $this->headers = $headers;
        return $this;
    }

    public function addHeader($header)
    {
        $this->headers[] = $header;
        return $this;
    }

    public function preform()
    {
        $ch = $this->cURL();

        curl_setopt($ch, CURLOPT_URL, $this->apiUrl);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_USERAGENT, $this->userAgent);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $this->headers);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYSTATUS, false);
        if (is_array($this->postFields) && count($this->postFields)) {
            curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($this->postFields));
        } else {
            if (!empty($this->postFields)) {
                curl_setopt($ch, CURLOPT_POSTFIELDS, $this->postFields);
            }
        }

        return curl_exec($ch);
    }

    /**
     * @return mixed
     * @throws SmartCCDGUTNetworkException
     */
    public function preformOrFail()
    {
        $preformResult = $this->preform();
        if ($preformResult === false) {
            throw new SmartCCDGUTNetworkException(curl_error($this->cURL()), curl_errno($this->cURL()));
        }
        return $preformResult;
    }

    /**
     * @return mixed
     * @throws SmartCCDGUTNetworkException
     */
    public function preformDecodeOrFail()
    {
        $preformResult = $this->preform();
        if ($preformResult === false) {
            throw new SmartCCDGUTNetworkException(curl_error($this->cURL()), curl_errno($this->cURL()));
        }
        $decodedResult = json_decode($preformResult);
        if (is_null($decodedResult)) {
            throw new SmartCCDGUTNetworkException(json_last_error_msg(), json_last_error());
        }
        return $decodedResult;
    }

    /**
     * @return mixed
     * @throws SmartCCDGUTNetworkException
     */
    public function preformThenClear()
    {
        try {
            return $this->preformOrFail();
        } finally {
            $this->clear();
        }
    }

    public function clear()
    {
        curl_close($this->cURL());
    }

    public function __get($name)
    {
        return $this->{$name};
    }
}

umask(0077);

CommandRouter::start();
